trigger:
  branches:
    include:
    - master

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly midnight (UTC) build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: | 
    git clone https://github.com/master-of-servers/ansible-test-lab.git
    cd ansible-test-lab && cd basic
    bash files/create_ssh_key.sh
    cp files/authorized_keys control/files
    cp files/id_rsa control/files
    cp files/id_rsa.pub control/files
    cp files/authorized_keys managed/files
    cp files/id_rsa managed/files
    cp files/id_rsa.pub managed/files
    docker-compose up -d --build
    sleep 40
    echo "Decrypting the vault file"
    docker exec -i basic-control-node ansible-vault decrypt /root/.ansible/group_vars/vault
    docker exec -i basic-control-node cat /root/.ansible/group_vars/vault
    echo "Encrypting the vault file"
    docker exec -i basic-control-node ansible-vault encrypt /root/.ansible/group_vars/vault
    docker exec -i basic-control-node cat /root/.ansible/group_vars/vault
    echo "Applying the hello playbook to the managed node"
    docker exec -i basic-control-node bash -c "cd ~/.ansible && ansible-playbook site.yml"
    # Enroll agent with ansible master
    docker ps
  displayName: 'Build and configure the basic ansible test environment'

- script: | 
    docker-compose down -v
  displayName: 'Tear down the basic ansible test environment'
  workingDirectory: ansible-test-lab/basic
